### ISSUE TITLE
[BUG] Attempt to generate WinUI event,  project compiles but events file not generated

### ISSUE THREAD

**Issue by harvinders** [reactiveui/Pharmacist#101]
**Describe the bug**
I am trying to generate events for a WinUI/UWP project. The UWP library project with reference to `Pharmacist.MsBuild` builds but fails to generate events file

**Steps To Reproduce**
1. Open visual studio 2019
2. Create a UWP C# library project
3. Add reference to WinUI 2.4 pre-release
4. Add nuget reference to `Pharmacist.MsBuild`
5. Change target to 1903 and min target to 1803
6. Build the project

repo project is [here](https://github.com/harvinders/pharmacist)

**Expected behavior**
Events class/file should have been generated

**Screenshots**
The solution doesn't show the `Pharmacist.MsBuild` reference for some reason
![image](https://user-images.githubusercontent.com/8557046/71762370-81b90000-2f22-11ea-846f-fb5aa2c547d7.png)

**Environment**

- OS:       Windows 1803
- Visual Studio 2019 16.4

**Comment by glennawatson** [comment]
Thanks, will take a look tomorrow for you.

**Comment by weitzhandler** [comment]
In my setup, the events file is generated, but events for many essential packages and namespaces such as `Windows.UI.Xaml.Controls.*` aren't being generated.

**Comment by harvinders** [comment]
It's it possible to share a minimal reproducible repo. Just want to check
how my repo is different from yours, and probably make some changes at my
end.

**Comment by glennawatson** [comment]
@weitzhandler can you open another issue since it's unrelated to this issue. Also make sure you include all NuGet packages you need to generate. Eg any core packages of Uno etc

**Comment by weitzhandler** [comment]
Np, deleted my posts.

**Comment by harvinders** [comment]
@glennawatson, Obviously you are busy with many other things, I am wondering if I can figure out what is wrong. I am not sure how to debug this, any pointers would be appreciated.

**Comment by glennawatson** [comment]
Your sample app has issues btw. 

You need to copy paste exactly how it is in the readme file on the main page the inclusions for pharmacist. Not sure if that will resolve your issue but worth fixing. 

The big one is there isn't the private asset so all your sub projects will be generating pharmacist events.

**Comment by harvinders** [comment]
@glennawatson  The app was created sometime back when just including these `PackageReference` were giving compilation error. I created another app (blank app template in visual studio 2019) and hand coded these two reference in the csproj. However, when I compile, I see visual studio reporting build successfully, but the visual studio hangs.

> The big one is there isn't the private asset so all your sub projects will be generating pharmacist events.
With this new blank app, I was hoping it would generate the events for UWP. Could you please explain your comment above. When you say ` sub projects` what do you mean? Do you mean all the included  `PackageReference`s?

**Comment by glennawatson** [comment]
The hanging bug I'm aware of and fixing at the moment. Should be another release in a day or so.

**Comment by glennawatson** [comment]
Sorry for the delay

Try https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

This uses a different way of generating the files.
