### ISSUE TITLE
feature: Add support for MsBuild Central Package Version

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/Pharmacist#105]
**Is your feature request related to a problem? Please describe.**

Recently I started migrating projects to [MsBuild Sdk Central Package Version](https://github.com/microsoft/MSBuildSdks/tree/master/src/CentralPackageVersions).  When I attempted to use Pharmacist in the following project I get errors [CentralPackageVersion](https://github.com/RLittlesII/demo/tree/master/msbuild/CentralPackageVersion).

**Describe the solution you'd like**

Worst case, I can use Central Package Version with Pharmacist.  Best case I can use Central Package Version with Pharmacist only in specific projects in my solution.

**Describe alternatives you've considered**

Removing Central Package Versioning.

**Describe suggestions on how to achieve the feature**

With my lack of knowledge on the subject I would assume that the MsBuild engine simply can't read the package version with. Pharmacist

**Additional context**

**Comment by glennawatson** [comment]
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

It no longer uses it own nuget package system, will instead deal with DLLs after provided by the source generator.
