### ISSUE TITLE
[BUG] Visual Studio 2019 hangs during project build

### ISSUE THREAD

**Issue by harvinders** [reactiveui/Pharmacist#112]
**Describe the bug**
After adding following lines to a newly created UWP project, the project build hangs visual studio.
```
<ItemGroup>
    <PackageReference Include="Pharmacist.MsBuild" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="Pharmacist.Common" Version="1.*" />
</ItemGroup>
```

**Steps To Reproduce**
1. Create a new UWP Blank app 
2. Edit the csproj with the above mentioned code snippet
3. Rebuild the csproj
4. Visual Studio hangs

**Expected behavior**
Visual studio should not hang.

**Environment**

- OS:       Windows 1803
- Visual Studio Version:   2019, 16.4.0

**Additional context**

**Comment by glennawatson** [comment]
This was solved during the 1.5.14 release.
