### ISSUE TITLE
Generate reactiveui-events for windows.web.ui.interop.webviewcontrol and friends

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/Pharmacist#12]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">We are looking for someone to PR in the UWP controls in webforms/wpf. See <a href="https://t.co/5d9TKO56XH">https://t.co/5d9TKO56XH</a> for specifics. Will be fleshing it out some more now that this has been announced.</p>&mdash; 𝓖eoffrey 𝓗untley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/993612918666158080?ref_src=twsrc%5Etfw">May 7, 2018</a></blockquote>

As per the announcement today we are looking for folks to send in the appropriate PR's to the ReactiveUI event builder that generates IObservables for all EventHandlers in the new public API that makes UWP controls run in WinForms and WPF:

https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/

See this API for specifics as an example:

https://docs.microsoft.com/en-us/uwp/api/windows.web.ui.interop.webviewcontrol

See ~/src/EventBuilder in the codebase.

**Comment by glennawatson** [comment]
This is already supported with Pharmacist 1.0.95
