### ISSUE TITLE
[BUG] Visual Studio 2019.16.5 hangs with Phamacist installed

### ISSUE THREAD

**Issue by rexebin** [reactiveui/Pharmacist#148]
Describe The Bug

After installing Phamacist.MsBuild and Phamacist.Common from Nuget to a newly created Xamarin project created from Prism Template. Restart Visual Studio 2019 Community and open the project. Visual Studio 2019 hangs after a few minutes at most. 

However it doesn't say unresponsive in Windows Task Manager. CPU and Memory are not busy at all. There is also a Visual Studio Delay Notification in the System Tray. 

I have to kill Visual Studio when this happens, it doesn't come back to life when this happens.  I suspect there is something in the work that blocks Visual Studio, a infinite loop or doing something that takes a extremely long time to complete.

Steps To Reproduce

1. Create a new Xamarin Prism project
1. Install Phamacist.MsBuild and Phamacist.Common to main application lib
1. Restart Visual Studio
1. Visual Studio hangs after a few minutes, sometimes after a few minutes, some times very quickly
1. Remove Phamacist.MsBuild and Phamacist.Common, Visual Studio does not hang.

Expected Behaviour
Visual studio should not hang.

Environment

OS: Windows 2004
Newly installed Visual Studio Version: 2019, 16.6.5, no extra extensions.

**Comment by Almis90** [comment]
Same issue with Visual Studio Version: 2019, 16.8.0 and Phamacist.MsBuild 1.9.1

**Comment by glennawatson** [comment]
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

This doesn't use the MSBuild system anymore, instead a source generator.
