### ISSUE TITLE
Xamarin.Forms Build fails after installing Pharmacist NuGets 

### ISSUE THREAD

**Issue by mwerickson** [reactiveui/Pharmacist#180]
**Describe the bug**
Build fails after installing Pharmacist

**Steps To Reproduce**
1. Install Phamacist nuget into shared project  (.Net Standard 2.0)
```
<PackageReference Include="Pharmacist.MsBuild" Version="1.*" PrivateAssets="all" />
<PackageReference Include="Pharmacist.Common" Version="1.*" />
```
2. Try to build application
3. See screenshot

**Expected behavior**
Build succeeds and all events are available as observables

**Screenshots**
![image](https://user-images.githubusercontent.com/8538717/99290648-9174c680-280c-11eb-8b09-936ab476ca95.png)

**Environment**

- OS:       Windows 10
- Device:   Desktop i9 with 64GB ram
- Version:   1.9.1
- Working Version: n/a
- Dev Env: VS2019 16.7.5 connected to MacBook Pro 10.15.7

**Additional context**

Seems to be only with a namespace of Xamarin.MacDev and the Shiny Geofence SetState method override.  Do I need to exclude these?  Or is there some other way to remove these build issues?

**Comment by DawidBester** [comment]
Also experiencing the same types of issue after installing Pharmacist 2.0.6 as described, all errors are in a file called Pharmacist.Nuget.g.cs, see screenshots. Any ideas on how to fix?:

![image](https://user-images.githubusercontent.com/33708055/104143678-51ede380-5425-11eb-8952-4aa88fed57fe.png)

![image](https://user-images.githubusercontent.com/33708055/104143697-75b12980-5425-11eb-9c74-833bc90ae2ae.png)

![image](https://user-images.githubusercontent.com/33708055/104143737-96797f00-5425-11eb-8c8f-e1efde8a1d22.png)

![image](https://user-images.githubusercontent.com/33708055/104143766-b4df7a80-5425-11eb-9e8f-db43f4c3b0a6.png)

![image](https://user-images.githubusercontent.com/33708055/104143792-ccb6fe80-5425-11eb-8316-b4568b4ded8e.png)

Uninstalling Pharmacist resolves the issue.

**Comment by glennawatson** [comment]
Can you give me a list of the NuGet packages installed? 

Seems just some language features are missing and probably worth updating to support them.

**Comment by DawidBester** [comment]
PackageReferences for the project as follows:

 <ItemGroup>
	
      <PackageReference Include="Microsoft.AppCenter" Version="4.1.0" />
      <PackageReference Include="Microsoft.AppCenter.Analytics" Version="4.1.0" />
      <PackageReference Include="Microsoft.AppCenter.Crashes" Version="4.1.0" />
      <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.3">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
      <PackageReference Include="Microsoft.NETCore.Platforms" Version="5.0.0" />
      <PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
      <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
      <PackageReference Include="NuGet.CommandLine" Version="5.8.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Plugin.StoreReview" Version="3.0.0-beta" />
      <PackageReference Include="Polly" Version="7.2.1" />
      <PackageReference Include="ReactiveUI" Version="13.0.38" />
      <PackageReference Include="ReactiveUI.Events.XamForms" Version="13.0.38" />
      <PackageReference Include="ReactiveUI.Fody" Version="13.0.38" />
      <PackageReference Include="ReactiveUI.XamForms" Version="13.0.38" />
      <PackageReference Include="refit" Version="5.2.4" />
      <PackageReference Include="Refit.HttpClientFactory" Version="5.2.4" />
      <PackageReference Include="SkiaSharp.Views.Forms" Version="2.80.2" />
      <PackageReference Include="sqlite-net-pcl" Version="1.7.335" />
      <PackageReference Include="Syncfusion.Licensing" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.Calculate" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.Core" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.DataGridExport" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.DataSource" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.GridCommon" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.SfChart" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.SfDataGrid" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.SfGauge" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.SfListView" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.SfMaskedEdit" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.SfNumericTextBox" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.SfPicker" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.Xamarin.SfRangeSlider" Version="18.4.0.33" />
      <PackageReference Include="Syncfusion.XlsIO.Net.Core" Version="18.4.0.33" />
      <PackageReference Include="System.AppContext" Version="4.3.0" />
      <PackageReference Include="System.Collections" Version="4.3.0" />
      <PackageReference Include="System.Collections.Concurrent" Version="4.3.0" />
      <PackageReference Include="System.ComponentModel.TypeConverter" Version="4.3.0" />
      <PackageReference Include="System.Console" Version="4.3.1" />
      <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
      <PackageReference Include="System.Diagnostics.Tools" Version="4.3.0" />
      <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
      <PackageReference Include="System.Globalization" Version="4.3.0" />
      <PackageReference Include="System.Globalization.Calendars" Version="4.3.0" />
      <PackageReference Include="System.IO" Version="4.3.0" />
      <PackageReference Include="System.IO.Compression" Version="4.3.0" />
      <PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
      <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
      <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
      <PackageReference Include="System.Linq" Version="4.3.0" />
      <PackageReference Include="System.Linq.Expressions" Version="4.3.0" />
      <PackageReference Include="System.Net.Http" Version="4.3.4" />
      <PackageReference Include="System.Net.Primitives" Version="4.3.1" />
      <PackageReference Include="System.Net.Sockets" Version="4.3.0" />
      <PackageReference Include="System.ObjectModel" Version="4.3.0" />
      <PackageReference Include="System.Reflection" Version="4.3.0" />
      <PackageReference Include="System.Reflection.Extensions" Version="4.3.0" />
      <PackageReference Include="System.Reflection.Primitives" Version="4.3.0" />
      <PackageReference Include="System.Resources.ResourceManager" Version="4.3.0" />
      <PackageReference Include="System.Runtime" Version="4.3.1" />
      <PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
      <PackageReference Include="System.Runtime.Handles" Version="4.3.0" />
      <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
      <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
      <PackageReference Include="System.Runtime.Numerics" Version="4.3.0" />
      <PackageReference Include="System.Runtime.Serialization.Formatters" Version="4.3.0" />
      <PackageReference Include="System.Runtime.Serialization.Primitives" Version="4.3.0" />
      <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.1" />
      <PackageReference Include="System.Security.Cryptography.Encoding" Version="4.3.0" />
      <PackageReference Include="System.Security.Cryptography.Primitives" Version="4.3.0" />
      <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
      <PackageReference Include="System.Text.Encoding" Version="4.3.0" />
      <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
      <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
      <PackageReference Include="System.Threading" Version="4.3.0" />
      <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
      <PackageReference Include="System.Threading.Timer" Version="4.3.0" />
      <PackageReference Include="System.ValueTuple" Version="4.5.0" />
      <PackageReference Include="System.Xml.ReaderWriter" Version="4.3.1" />
      <PackageReference Include="System.Xml.XDocument" Version="4.3.0" />
      <PackageReference Include="System.Xml.XmlDocument" Version="4.3.0" />
      <PackageReference Include="Xamarin.Build.Download" Version="0.10.0" />
      <PackageReference Include="Xamarin.Essentials" Version="1.6.0" />
      <PackageReference Include="Xamarin.Forms" Version="4.8.0.1821" />
      <PackageReference Include="Xamarin.Forms.Visual.Material" Version="4.8.0.1821" />
    
    </ItemGroup>

**Comment by glennawatson** [comment]
Thanks, I'll have a look at what SyncFusion is doing special since that is the one that seems to be causing an issue. Won't be til tomorrow.

Also if you're using Pharmacist you won't need ReactiveUI.Events.XamForms but that's not what's causing this issue.

**Comment by DawidBester** [comment]
Thanks for the the assistance and additional information.

**Comment by glennawatson** [comment]
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

This will handle these cases.
