### ISSUE TITLE
[BUG] Unable to install Pharmacist package into Xamarin Forms 4.8.0.1821project

### ISSUE THREAD

**Issue by DawidBester** [reactiveui/Pharmacist#196]
**Describe the bug**

I'm unable to install Pharmacist into Xamarin Forms 4.8.0.1821 project which targets netstandard2.0.

Package install fails with the following message.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Pharmacist 2.0.6 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Pharmacist 2.0.6 supports: net5.0 (.NETCoreApp,Version=v5.0) / any	

The rest of the required Pharmacist packages install without a problem.

**Steps To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

- OS:       
- Device:   
- Version:   
- Working Version: 

**Additional context**

**Comment by glennawatson** [comment]
```
<ItemGroup>
    <PackageReference Include="Pharmacist.MsBuild" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="Pharmacist.Common" Version="1.*" />
</ItemGroup>
```

Need to install those 2 packages, the `Pharmacist` package is a DotNet tool.
