### ISSUE TITLE
No actual assembly ICSharpCode.Decompiler available for net5.0

### ISSUE THREAD

**Issue by rstm-sf** [reactiveui/Pharmacist#204]
No actual assembly ICSharpCode.Decompiler available for net5.0

**Describe the bug**
```
/home/vsts/work/1/s/nukebuild/_build.csproj : warning NU1603: Pharmacist.Core 2.0.6 depends on ICSharpCode.Decompiler (>= 2.0.6) but ICSharpCode.Decompiler 2.0.6 was not found. An approximate best match of ICSharpCode.Decompiler 2.3.0 was resolved.
/home/vsts/work/1/s/nukebuild/_build.csproj : warning NU1701: Package 'ICSharpCode.Decompiler 2.3.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
/home/vsts/work/1/s/nukebuild/_build.csproj : warning NU1701: Package 'ICSharpCode.NRefactory 5.5.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
```
Pharmacist has its own [ICSharpCode.Decompiler](https://github.com/reactiveui/Pharmacist/blob/357b54abbddd36b31ade933caa9e1bff486003ec/src/Pharmacist.Core/Pharmacist.Core.csproj#L22) which is not [covered](https://github.com/reactiveui/Pharmacist/blob/357b54abbddd36b31ade933caa9e1bff486003ec/src/ICSharpCode.Decompiler/ICSharpCode.Decompiler.csproj#L20)

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Go to Avalonia Build Pipelines https://dev.azure.com/AvaloniaUI/AvaloniaUI/_build/results?buildId=12768&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=f33089cd-d3fe-578c-2c5e-4ee560e10a0d
2. Click on Linux -> Run Nuke
3. Scroll down to end
TypeLoadException: Could not load type 'ICSharpCode.Decompiler.TypeSystem.ICompilation' from assembly 'ICSharpCode.Decompiler, Version=2.3.0.1834, Culture=neutral, PublicKeyToken=d4bfe873e7598c49'.

**Expected behavior**
Builds and runs without warnings and exceptions

**Screenshots**

**Environment**

- OS:       Windows, Mac, Linux
- Device:   
- Version:   2.0.6
- Working Version: 

**Additional context**

Changes https://github.com/AvaloniaUI/Avalonia/commit/b265eff00d5db003bca582eeb83593bb07859b04

**Comment by glennawatson** [comment]
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

This does not rely on ICSharpCode.Decompiler.
