### ISSUE TITLE
The "PharmacistNuGetTask" task failed unexpectedly. Having a problem with offline development and Pharmacist 2.0.8 nuget

### ISSUE THREAD

**Issue by lltwist** [reactiveui/Pharmacist#234]
When building proj being offline, i get an exception from Pharmacist.MSBuild which is failed with PharmacistNuGetTask.GetPackages.

.csproj :
<PackageReference Include="Pharmacist.Common" Version="2.0.8" />
<PackageReference Include="Pharmacist.MSBuild" Version="2.0.8" PrivateAssets="all" />

Also tried to set <PharmacistGlobalPackages> true/false - no changes.

globalPackagesFolder in nuget.condig is added.

How one can setup environment or some other workarounds to properly generate .Events() being offline?

**Comment by glennawatson** [comment]
You can't at the moment build offline. It's a feature of the source generator version I been working on. 

I have a property changed one I want to get out first but then will work on finishing the source gen pharmacist.

**Comment by glennawatson** [comment]
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

This will handle offline changes.
