### ISSUE TITLE
feature: MAUI Support

### ISSUE THREAD

**Issue by stevefan1999-personal** [reactiveui/Pharmacist#343]
**Is your feature request related to a problem? Please describe.**
There is an error regarding to use Pharmacist on MAUI
```
1>C:\Users\steve\.nuget\packages\pharmacist.msbuild\1.9.1\buildTransitive\netstandard2.0\Pharmacist.MSBuild.targets(48,5): error : Neither TargetFramework nor ProjectTypeGuids have been correctly set.
1>Done building project "MauiWithGraphQL.csproj" -- FAILED.
1>C:\Users\steve\.nuget\packages\pharmacist.msbuild\1.9.1\buildTransitive\netstandard2.0\Pharmacist.MSBuild.targets(48,5): error : Neither TargetFramework nor ProjectTypeGuids have been correctly set.
```
Although `TargetFrameworks` is well set:
```
	<PropertyGroup>
		<TargetFrameworks>net6.0-ios;net6.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net6.0-windows10.0.19041.0</TargetFrameworks>
```

**Describe the solution you'd like**

To have seamless integration of MAUI

**Describe alternatives you've considered**
Just manually rewrite the events

**Comment by mysteryx93** [comment]
I'm having the same problem in an Avalonia project.

**Comment by glennawatson** [comment]
We won't be extending support, pushing instead ReactiveMarble.ObservableEvents

I've noted the issues you've been having @mysteryx93 over there and hoping for some time this weekend to fix them.
