### ISSUE TITLE
[Question] Issue with Pharmacist NuGet Task

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/Pharmacist#44]
**Describe the bug**

`The "PharmacistNuGetTask" task was not given a value for the required "TargetFramework".`

**Steps To Reproduce**
There is a reproduction repository provided
https://github.com/RLittlesII/Rfid.Observables/tree/feature/tsl-demo

**Expected behavior**

That Pharmacist either generates observables, or tells me why it cant.

**Environment**

- macOSX: It appears to build fine
- Windows I receive the listed error

**Additional context**

I also installed the Pharmacist global tool.  That executed fine, generated events, none of the events were from the [Tsl.AsciiProtocol](https://www.nuget.org/packages/Tsl.AsciiProtocol/) package.  I suspect because there are events, but I am not sure that event handlers are defined in that nuget.  I loaded it in dotpeek and poked around a bit.

**Comment by glennawatson** [comment]
Is this still an issue @RLittlesII

**Comment by RLittlesII** [comment]
I don't believe this is a valid issue based on what I know of Pharmacist now.
