### ISSUE TITLE
[BUG] Can't handle generic base classes

### ISSUE THREAD

**Issue by modplug** [reactiveui/Pharmacist#80]
**Describe the bug**

Pharmasist does not pick up events contained in a base class with generics.

public class TabbedPage : MultiPage<Page>, IBarElement, IElementConfiguration<TabbedPage>

**Steps To Reproduce**

Add pharmacist to your Xamarin Forms project.
Try to access observables from events generated from a page with generics.
public class TabbedPage : MultiPage<Page>, IBarElement, IElementConfiguration<TabbedPage>

Events like CurrentPageChanged is not generated. 

**Environment**
Xamarin Forms 4.3

**Comment by glennawatson** [comment]
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/ and https://github.com/reactivemarbles/ObservableEventsSourceGenerator

This will handle generic base classes I believe.
